<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Application\SchoolAccount.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArchitectureTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="GovUK.Dfe.AcademiesApi.Client" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
  </ItemGroup>
</Project>
