@API_HostAddress = http://localhost:5100

### Get organisation with 7-digit laestab (expected 200)
GET {{API_HostAddress}}/organisations/1234567
Accept: application/json

### Get organisation with 5-digit laestab (expected 400)
GET {{API_HostAddress}}/organisations/12345
Accept: application/json