<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <EnableGovUkFrontendSupport>true</EnableGovUkFrontendSupport>
    <RestoreGovUkFrontendStylesheet>false</RestoreGovUkFrontendStylesheet>
    <RestoreGovUkFrontendNpmPackage>true</RestoreGovUkFrontendNpmPackage>
    <RestoreGovUkFrontendSupportPackage>true</RestoreGovUkFrontendSupportPackage>
    <UserSecretsId>f14c3870-7ac6-404b-a007-f489e1b708d6</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <GovUkFrontendAssetsDirectory>/wwwroot</GovUkFrontendAssetsDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Infrastructure\SchoolAccount.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" />
    <PackageReference Include="GovUk.Frontend.AspNetCore" />
  </ItemGroup>
</Project>
